- name: Flutter pub get
        run: flutter pub get

      - name: Install Android SDK components
        run: |
          SDKMANAGER="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
          yes | "${SDKMANAGER}" --licenses
          yes | "${SDKMANAGER}" "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Ensure gradlew is executable
        run: chmod +x android/gradlew

      - name: Build APK (debug)
        run: flutter build apk --debug -v

      - name: Build APK (release)
        run: flutter build apk --release -v

      - name: Upload APK artifact (release)
        uses: actions/upload-artifact@v4
        with:
          name: mattajirs-app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk